export interface TikTokEmoji {
  id: string;
  name: string;
  unicode: string;
  imagePath: string;
  shortcode: string;
  meaning: string;
  shortMeaning: string;
  category: string;
  usage: string;
  urlSlug: string; // 新增URL友好的slug
}

export const tiktokEmojis: TikTokEmoji[] = [
  { id: '1', name: 'smile', unicode: '😇', imagePath: '/emojis/smile.png', shortcode: '[smile]', meaning: 'A small, round, pink smiling face used to show happiness or appreciation.', shortMeaning: 'Show happiness or appreciation', category: 'emotions', usage: 'A small, round, pink smiling face used to show happiness or appreciation.', urlSlug: 'tiktok-smile' },
  { id: '2', name: 'happy', unicode: '😊', imagePath: '/emojis/happy.png', shortcode: '[happy]', meaning: 'A peach-colored face with squinty eyes and a big open mouth, expressing extreme excitement.', shortMeaning: 'Extreme excitement', category: 'emotions', usage: 'A peach-colored face with squinty eyes and a big open mouth, expressing extreme excitement.', urlSlug: 'tiktok-happy' },
  { id: '3', name: 'angry', unicode: '😠', imagePath: '/emojis/angry.png', shortcode: '[angry]', meaning: 'A red face with furrowed brows, used to convey anger or displeasure.', shortMeaning: 'Anger or displeasure', category: 'emotions', usage: 'A red face with furrowed brows, used to convey anger or displeasure.', urlSlug: 'tiktok-angry' },
  { id: '4', name: 'cry', unicode: '😢', imagePath: '/emojis/cry.png', shortcode: '[cry]', meaning: 'A blue face with tears streaming down, representing sadness or emotional overwhelm.', shortMeaning: 'Sadness or crying', category: 'emotions', usage: 'A blue face with tears streaming down, representing sadness or emotional overwhelm.', urlSlug: 'tiktok-cry' },
  { id: '5', name: 'embarrassed', unicode: '😳', imagePath: '/emojis/embarrassed.png', shortcode: '[embarrassed]', meaning: 'A face with rosy cheeks and a shy smile, indicating embarrassment or shyness.', shortMeaning: 'Embarrassment or shyness', category: 'emotions', usage: 'A face with rosy cheeks and a shy smile, indicating embarrassment or shyness.', urlSlug: 'tiktok-embarrassed' },
  { id: '6', name: 'surprised', unicode: '😮', imagePath: '/emojis/surprised.png', shortcode: '[surprised]', meaning: 'A face with wide eyes and an open mouth, expressing shock or surprise.', shortMeaning: 'Shock or surprise', category: 'emotions', usage: 'A face with wide eyes and an open mouth, expressing shock or surprise.', urlSlug: 'tiktok-surprised' },
  { id: '7', name: 'wronged', unicode: '😔', imagePath: '/emojis/wronged.png', shortcode: '[wronged]', meaning: 'A yellow face with sad eyes and two fingers pointing at each other, indicating shyness or embarrassment.', shortMeaning: 'Shyness or embarrassment', category: 'emotions', usage: 'A yellow face with sad eyes and two fingers pointing at each other, indicating shyness or embarrassment.', urlSlug: 'tiktok-wronged' },
  { id: '8', name: 'shout', unicode: '😤', imagePath: '/emojis/shout.png', shortcode: '[shout]', meaning: 'A face with an open mouth, often used to express excitement or yelling.', shortMeaning: 'Excitement or yelling', category: 'emotions', usage: 'A face with an open mouth, often used to express excitement or yelling.', urlSlug: 'tiktok-shout' },
  { id: '9', name: 'flushed', unicode: '😳', imagePath: '/emojis/flushed.png', shortcode: '[flushed]', meaning: 'A face with red cheeks, indicating embarrassment or shyness.', shortMeaning: 'Embarrassment or shyness', category: 'emotions', usage: 'A face with red cheeks, indicating embarrassment or shyness.', urlSlug: 'tiktok-flushed' },
  { id: '10', name: 'yummy', unicode: '😋', imagePath: '/emojis/yummy.png', shortcode: '[yummy]', meaning: 'A face licking its lips, expressing deliciousness or craving for food.', shortMeaning: 'Delicious or craving', category: 'expressions', usage: 'A face licking its lips, expressing deliciousness or craving for food.', urlSlug: 'tiktok-yummy' },
  { id: '11', name: 'complacent', unicode: '😏', imagePath: '/emojis/complacent.png', shortcode: '[complacent]', meaning: 'A smug face with a self-satisfied smile, indicating complacency.', shortMeaning: 'Complacency', category: 'emotions', usage: 'A smug face with a self-satisfied smile, indicating complacency.', urlSlug: 'tiktok-complacent' },
  { id: '12', name: 'drool', unicode: '🤤', imagePath: '/emojis/drool.png', shortcode: '[drool]', meaning: 'A face with drool coming out of its mouth, indicating hunger or desire.', shortMeaning: 'Hunger or desire', category: 'emotions', usage: 'A face with drool coming out of its mouth, indicating hunger or desire.', urlSlug: 'tiktok-drool' },
  { id: '13', name: 'scream', unicode: '😱', imagePath: '/emojis/scream.png', shortcode: '[scream]', meaning: 'A face with wide eyes and an open mouth, expressing fear or shock.', shortMeaning: 'Fear or shock', category: 'emotions', usage: 'A face with wide eyes and an open mouth, expressing fear or shock.', urlSlug: 'tiktok-scream' },
  { id: '14', name: 'weep', unicode: '😿', imagePath: '/emojis/weep.png', shortcode: '[weep]', meaning: 'A face with tears, indicating deep sadness or sorrow.', shortMeaning: 'Deep sadness or sorrow', category: 'emotions', usage: 'A face with tears, indicating deep sadness or sorrow.', urlSlug: 'tiktok-weep' },
  { id: '15', name: 'speechless', unicode: '😶', imagePath: '/emojis/speechless.png', shortcode: '[speechless]', meaning: 'A face with a hand over its mouth, indicating shock or being speechless.', shortMeaning: 'Shock or speechless', category: 'emotions', usage: 'A face with a hand over its mouth, indicating shock or being speechless.', urlSlug: 'tiktok-speechless' },
  { id: '16', name: 'funnyface', unicode: '🤪', imagePath: '/emojis/funnyface.png', shortcode: '[funnyface]', meaning: 'A silly face with exaggerated features, used to indicate humor.', shortMeaning: 'Humor', category: 'emotions', usage: 'A silly face with exaggerated features, used to indicate humor.', urlSlug: 'tiktok-funnyface' },
  { id: '17', name: 'laughwithtears', unicode: '🤣', imagePath: '/emojis/laughwithtears.png', shortcode: '[laughwithtears]', meaning: 'A face laughing with tears streaming down, indicating extreme laughter.', shortMeaning: 'Extreme laughter', category: 'emotions', usage: 'A face laughing with tears streaming down, indicating extreme laughter.', urlSlug: 'tiktok-laughwithtears' },
  { id: '18', name: 'wicked', unicode: '😏', imagePath: '/emojis/wicked.png', shortcode: '[wicked]', meaning: 'A mischievous face with a sly smile, indicating wickedness or playfulness.', shortMeaning: 'Wickedness or playfulness', category: 'emotions', usage: 'A mischievous face with a sly smile, indicating wickedness or playfulness.', urlSlug: 'tiktok-wicked' },
  { id: '19', name: 'facewithrollingeyes', unicode: '🙄', imagePath: '/emojis/facewithrollingeyes.png', shortcode: '[facewithrollingeyes]', meaning: 'A face rolling its eyes, indicating annoyance or disbelief.', shortMeaning: 'Annoyance or disbelief', category: 'emotions', usage: 'A face rolling its eyes, indicating annoyance or disbelief.', urlSlug: 'tiktok-facewithrollingeyes' },
  { id: '20', name: 'sulk', unicode: '😒', imagePath: '/emojis/sulk.png', shortcode: '[sulk]', meaning: 'A face with a frown, indicating sulking or disappointment.', shortMeaning: 'Sulking or disappointment', category: 'emotions', usage: 'A face with a frown, indicating sulking or disappointment.', urlSlug: 'tiktok-sulk' },
  { id: '21', name: 'thinking', unicode: '🤔', imagePath: '/emojis/thinking.png', shortcode: '[thinking]', meaning: 'A face with a hand on its chin, indicating deep thought or contemplation.', shortMeaning: 'Deep thought', category: 'emotions', usage: 'A face with a hand on its chin, indicating deep thought or contemplation.', urlSlug: 'tiktok-thinking' },
  { id: '22', name: 'lovely', unicode: '🥰', imagePath: '/emojis/lovely.png', shortcode: '[lovely]', meaning: 'A face with hearts in its eyes, indicating love or admiration.', shortMeaning: 'Love or admiration', category: 'emotions', usage: 'A face with hearts in its eyes, indicating love or admiration.', urlSlug: 'tiktok-lovely' },
  { id: '23', name: 'greedy', unicode: '🤑', imagePath: '/emojis/greedy.png', shortcode: '[greedy]', meaning: 'A face with a greedy smile, indicating greed or desire for more.', shortMeaning: 'Greed or desire', category: 'emotions', usage: 'A face with a greedy smile, indicating greed or desire for more.', urlSlug: 'tiktok-greedy' },
  { id: '24', name: 'wow', unicode: '😯', imagePath: '/emojis/wow.png', shortcode: '[wow]', meaning: 'A face with wide eyes and an open mouth, expressing amazement or wonder.', shortMeaning: 'Amazement or wonder', category: 'emotions', usage: 'A face with wide eyes and an open mouth, expressing amazement or wonder.', urlSlug: 'tiktok-wow' },
  { id: '25', name: 'joyful', unicode: '😆', imagePath: '/emojis/joyful.png', shortcode: '[joyful]', meaning: 'A face with a big smile and sparkling eyes, indicating joy or happiness.', shortMeaning: 'Joy or happiness', category: 'emotions', usage: 'A face with a big smile and sparkling eyes, indicating joy or happiness.', urlSlug: 'tiktok-joyful' },
  { id: '26', name: 'hehe', unicode: '😄', imagePath: '/emojis/hehe.png', shortcode: '[hehe]', meaning: 'A face with a mischievous grin, indicating a light-hearted or playful mood.', shortMeaning: 'Playful mood', category: 'emotions', usage: 'A face with a mischievous grin, indicating a light-hearted or playful mood.', urlSlug: 'tiktok-hehe' },
  { id: '27', name: 'slap', unicode: '🤚', imagePath: '/emojis/slap.png', shortcode: '[slap]', meaning: 'A face with a hand raised, indicating a slap or playful hit.', shortMeaning: 'Slap or playful hit', category: 'gestures', usage: 'A face with a hand raised, indicating a slap or playful hit.', urlSlug: 'tiktok-slap' },
  { id: '28', name: 'tears', unicode: '😭', imagePath: '/emojis/tears.png', shortcode: '[tears]', meaning: 'A face with tears, indicating sadness or emotional release.', shortMeaning: 'Sadness or emotional release', category: 'emotions', usage: 'A face with tears, indicating sadness or emotional release.', urlSlug: 'tiktok-tears' },
  { id: '29', name: 'stun', unicode: '😵', imagePath: '/emojis/stun.png', shortcode: '[stun]', meaning: 'A face with a shocked expression, indicating surprise or disbelief.', shortMeaning: 'Surprise or disbelief', category: 'emotions', usage: 'A face with a shocked expression, indicating surprise or disbelief.', urlSlug: 'tiktok-stun' },
  { id: '30', name: 'cute', unicode: '🥰', imagePath: '/emojis/cute.png', shortcode: '[cute]', meaning: 'A face with a sweet smile, indicating cuteness or affection.', shortMeaning: 'Cuteness or affection', category: 'emotions', usage: 'A face with a sweet smile, indicating cuteness or affection.', urlSlug: 'tiktok-cute' },
  { id: '31', name: 'blink', unicode: '😉', imagePath: '/emojis/blink.png', shortcode: '[blink]', meaning: 'A face with one eye closed, indicating a wink or playful gesture.', shortMeaning: 'Wink or playful gesture', category: 'emotions', usage: 'A face with one eye closed, indicating a wink or playful gesture.', urlSlug: 'tiktok-blink' },
  { id: '32', name: 'disdain', unicode: '🙄', imagePath: '/emojis/disdain.png', shortcode: '[disdain]', meaning: 'A face with a raised eyebrow, indicating disdain or disapproval.', shortMeaning: 'Disdain or disapproval', category: 'emotions', usage: 'A face with a raised eyebrow, indicating disdain or disapproval.', urlSlug: 'tiktok-disdain' },
  { id: '33', name: 'astonish', unicode: '😲', imagePath: '/emojis/astonish.png', shortcode: '[astonish]', meaning: 'A face with wide eyes and raised eyebrows, indicating astonishment.', shortMeaning: 'Astonishment', category: 'emotions', usage: 'A face with wide eyes and raised eyebrows, indicating astonishment.', urlSlug: 'tiktok-astonish' },
  { id: '34', name: 'rage', unicode: '😡', imagePath: '/emojis/rage.png', shortcode: '[rage]', meaning: 'A face with a furious expression, indicating intense anger.', shortMeaning: 'Intense anger', category: 'emotions', usage: 'A face with a furious expression, indicating intense anger.', urlSlug: 'tiktok-rage' },
  { id: '35', name: 'cool', unicode: '😎', imagePath: '/emojis/cool.png', shortcode: '[cool]', meaning: 'A face with sunglasses, indicating coolness or confidence.', shortMeaning: 'Coolness or confidence', category: 'emotions', usage: 'A face with sunglasses, indicating coolness or confidence.', urlSlug: 'tiktok-cool' },
  { id: '36', name: 'excited', unicode: '🤩', imagePath: '/emojis/excited.png', shortcode: '[excited]', meaning: 'A face with sparkling eyes and a big smile, indicating excitement.', shortMeaning: 'Excitement', category: 'emotions', usage: 'A face with sparkling eyes and a big smile, indicating excitement.', urlSlug: 'tiktok-excited' },
  { id: '37', name: 'proud', unicode: '😌', imagePath: '/emojis/proud.png', shortcode: '[proud]', meaning: 'A face with a smug smile, indicating pride or satisfaction.', shortMeaning: 'Pride or satisfaction', category: 'emotions', usage: 'A face with a smug smile, indicating pride or satisfaction.', urlSlug: 'tiktok-proud' },
  { id: '38', name: 'smileface', unicode: '🙂', imagePath: '/emojis/smileface.png', shortcode: '[smileface]', meaning: 'A face with a big smile, indicating happiness or friendliness.', shortMeaning: 'Happiness or friendliness', category: 'emotions', usage: 'A face with a big smile, indicating happiness or friendliness.', urlSlug: 'tiktok-smileface' },
  { id: '39', name: 'evil', unicode: '😈', imagePath: '/emojis/evil.png', shortcode: '[evil]', meaning: 'A face with a devilish grin, indicating mischief or evil intent.', shortMeaning: 'Mischief or evil intent', category: 'emotions', usage: 'A face with a devilish grin, indicating mischief or evil intent.', urlSlug: 'tiktok-evil' },
  { id: '40', name: 'angel', unicode: '😇', imagePath: '/emojis/angel.png', shortcode: '[angel]', meaning: 'A face with a halo, indicating innocence or goodness.', shortMeaning: 'Innocence or goodness', category: 'emotions', usage: 'A face with a halo, indicating innocence or goodness.', urlSlug: 'tiktok-angel' },
  { id: '41', name: 'laugh', unicode: '😂', imagePath: '/emojis/laugh.png', shortcode: '[laugh]', meaning: 'A face laughing, indicating joy or amusement.', shortMeaning: 'Joy or amusement', category: 'emotions', usage: 'A face laughing, indicating joy or amusement.', urlSlug: 'tiktok-laugh' },
  { id: '42', name: 'pride', unicode: '😤', imagePath: '/emojis/pride.png', shortcode: '[pride]', meaning: 'A face with a proud expression, indicating self-satisfaction.', shortMeaning: 'Self-satisfaction', category: 'emotions', usage: 'A face with a proud expression, indicating self-satisfaction.', urlSlug: 'tiktok-pride' },
  { id: '43', name: 'nap', unicode: '😴', imagePath: '/emojis/nap.png', shortcode: '[nap]', meaning: 'A face with closed eyes, indicating sleepiness or a desire to nap.', shortMeaning: 'Sleepiness or desire to nap', category: 'emotions', usage: 'A face with closed eyes, indicating sleepiness or a desire to nap.', urlSlug: 'tiktok-nap' },
  { id: '44', name: 'loveface', unicode: '😍', imagePath: '/emojis/loveface.png', shortcode: '[loveface]', meaning: 'A face with heart-shaped eyes, indicating love or infatuation.', shortMeaning: 'Love or infatuation', category: 'emotions', usage: 'A face with heart-shaped eyes, indicating love or infatuation.', urlSlug: 'tiktok-loveface' },
  { id: '45', name: 'awkward', unicode: '😅', imagePath: '/emojis/awkward.png', shortcode: '[awkward]', meaning: 'A face with a nervous smile, indicating awkwardness or discomfort.', shortMeaning: 'Awkwardness or discomfort', category: 'emotions', usage: 'A face with a nervous smile, indicating awkwardness or discomfort.', urlSlug: 'tiktok-awkward' },
  { id: '46', name: 'shock', unicode: '😨', imagePath: '/emojis/shock.png', shortcode: '[shock]', meaning: 'A face with a shocked expression, indicating surprise or disbelief.', shortMeaning: 'Surprise or disbelief', category: 'emotions', usage: 'A face with a shocked expression, indicating surprise or disbelief.', urlSlug: 'tiktok-shock' },
];